### ISSUE TITLE
replace default view in laravelbackpackers

### ISSUE THREAD

**Issue by sokvebolkol** [Laravel-Backpack/Base#425] opened 2020-03-04 04:54 UTC
# Bug report

### What I did:
Hi there,
My problem is that I can't return to my view!
I just want to replace default view in backpackers. I have created file named dashboard.blade.php by following @lloy0076 instructed.
I don't want to push data from AdminController . I want to create own view and do what I want.
### What I expected to happen:
return to my own view name dashboard.blade.php
### What happened:
It stills return to default view
### What I've already tried to fix it:
Here is my AdminController:

```php
 public function dashboard()
    {
        $this->data['title'] = trans('backpack::base.dashboard'); // set the page title

        return view(backpack_view('dashboard'), $this->data);
    }
```

**Comment by tabacitu** [comment] 2020-03-04 10:26
@sokvebolkol I'm afraid I don't understand what you're trying to do, and where you're getting stuck. But maybe this helps: to overwrite the default dashboard view, you should create this file, and do whatever you want inside it:

![Screenshot 2020-03-04 at 12 24 38](https://user-images.githubusercontent.com/1032474/75870164-45ffc100-5e13-11ea-8673-9308be0cd819.png)

Closing this as it's certainly not a bug - best asked on Gitter / StackOverflow / Reddit.

**Closed by tabacitu** 2020-03-04 10:26 UTC
Labels: triage
