### ISSUE TITLE
Make registration redirect use config "route_prefix"

### ISSUE THREAD

**Issue by giovannipds** [Laravel-Backpack/Base#58] opened 2016-11-15 12:15 UTC
Hello! I'm testing this application and until now, seems like an awesome work! Congratulations, seriously!

I saw that RegisterController is not using the config "route_prefix" variable, so in my case, where I'm not using "/admin", it doesn't redirect properly. Is there a way to solve this?

Regards, Gio.

**Comment by b8ne** [comment] 2016-12-12 10:56
Just an FYI @tabacitu I also found this in Generator's stub for Controllers, for the model route.

**Comment by tabacitu** [comment] 2016-12-13 06:29
Hmm... this might prove tricky, since we can't use config values when setting the values for PHP attributes. But something like this in our Backpack auth controllers _should_ work. Can you please confirm?

```diff
namespace Backpack\Base\app\Http\Controllers\Auth;

use Backpack\Base\app\Http\Controllers\Controller;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\Request;
use Validator;

class RegisterController extends Controller
{
    protected $data = []; // the information we send to the view

    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */
    use RegistersUsers;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = 'admin/dashboard';

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
+       $this->redirectTo = config('backpack.base.route_prefix').'/dashboard';
    }
```

Cheers!

**Comment by michaellindahl** [comment] 2016-12-31 06:14
This is a duplicate of Issue #45 and can be closed. I've validated that ce68c47 fixes this

**Comment by tabacitu** [comment] 2017-01-02 07:11
Great, thanks Michael. Cheers!

**Closed by tabacitu** 2017-01-02 07:11 UTC
