### ISSUE TITLE
separate login/register forms for users and admins

### ISSUE THREAD

**Issue by mpixelz** [Laravel-Backpack/Base#374] opened 2019-05-04 17:47 UTC
# Bug report

### What I did:
i have 2 tables `users` and `admins`.. i have migration and models done and also updated the BackpackUser class to use admins table. 

Both my tables have different set of columns, admins have name and email where as users have first name and last name instead of name. 

i was getting ``Uninitialized string offset: 0`` on ClassLoader.php
after i added backpack guards in auth.php (using direct path to backpackuser class instead of config path) this issue went away

### What I expected to happen:
When i try to register, it should register the user as admin (from backpack backend) and register user to users table when done from frontend.

### What happened:
im getting: 
```SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `admins` (`email`, `password`, `updated_at`, `created_at`) values (a@hotmail.com, $2y$10$MeNMP4gvuFWIhLKhqgU8Y.7U9xGU/DkOVag08QCE83qGzBL6vvk9., 2019-05-04 17:39:11, 2019-05-04 17:39:11))```

### Backpack, Laravel, PHP, DB version:
new project all updated versions on php 7.2

**Comment by mpixelz** [comment] 2019-05-07 19:54
anyone?

**Comment by tabacitu** [comment] 2019-05-08 08:12
Hi @mpixelz ,

This doesn't sound like a Backpack bug - it's an SQL error from your custom table. 

It looks like your ```name``` column in the ```admins``` table doesn't have a default value. That's what the error says - that's what's happening :-) Maybe you're not passing the name from the register form for some reason? 

Either way, does not look like a Backpack bug. Closing this.

Cheers!

**Closed by tabacitu** 2019-05-08 08:12 UTC
Labels: triage

**Comment by mpixelz** [comment] 2019-05-08 15:44
but it does. Ive copied the exact schema and model of User. in my request i do have name on my form.
using the instructions from the backpack website, i was getting:
`Uninitialized string offset: 0`  on ClassLoader.php
i changed my auth.php (providers) instead of config('backpack.base.user_model_fqn’) i used `App\Models\BackpackUser::class,` which resolved this error but then i started getting the error i mentioned in the OP.

**Comment by pxpm** [comment] 2019-05-08 18:35
@mpixelz maybe the problem is that you have your config cached before changing it.

Could you please use the "_backpack way_" but do a **php artisan config:cache** (it will clear the cache an re-cache config again)

MC

**Comment by mpixelz** [comment] 2019-05-09 19:18
@pxpm this worked for the first error.. but still cant register admin user..
The form does have name input.. ive used dd() in the backpack auth register controller and i do get $data['name'] but it still says 
```
SQLSTATE[HY000]: General error: 1364 Field 'name' doesn't have a default value (SQL: insert into `admins` (`email`, `password`, `updated_at`, `created_at`) values (a@a.com, $2y$10$wBWqemVAM8Etm0sQuQLbQ.hpqK9mtye.y3pYpCrzFIAwrgUDgKsSe, 2019-05-09 19:16:13, 2019-05-09 19:16:13))
```

**Comment by pxpm** [comment] 2019-05-09 19:23
Check for $fillable property on model.

`insert into `admins` (`email`, `password`, `updated_at`, `created_at`)`

You are not trying to insert name in query, but you have it as a requirement in database design.

**Comment by mpixelz** [comment] 2019-05-09 19:24
here is my Admin model
```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Backpack\CRUD\CrudTrait; // <------------------------------- this one
use Spatie\Permission\Traits\HasRoles;// <---------------------- and this one

class Admin extends Authenticatable
{
    use Notifiable;
    use CrudTrait; // <----- this
    use HasRoles; // <------ and this

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

```

**Comment by pxpm** [comment] 2019-05-09 19:37
I cannot reproduce that issue. 
Could you provide a more complete Log **ONLY ABOUT THIS ISSUE** Located in storage/logs/laravel.log

It might be something about guards, but not sure about it.

**Comment by mpixelz** [comment] 2019-05-09 19:45
here is the complete log:
```
[2019-05-09 19:45:12] local.ERROR: Uninitialized string offset: 0 {"exception":"[object] (ErrorException(code: 0): Uninitialized string offset: 0 at /Users/mac1/Sites/StudentPortal2/vendor/composer/ClassLoader.php:375)
[stacktrace]
#0 /Users/mac1/Sites/StudentPortal2/vendor/composer/ClassLoader.php(375): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Uninitialized s...', '/Users/mac1/Sit...', 375, Array)
#1 /Users/mac1/Sites/StudentPortal2/vendor/composer/ClassLoader.php(351): Composer\\Autoload\\ClassLoader->findFileWithExtension('', '.php')
#2 /Users/mac1/Sites/StudentPortal2/vendor/composer/ClassLoader.php(321): Composer\\Autoload\\ClassLoader->findFile('')
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('')
#4 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(170): spl_autoload_call('')
#5 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(48): Illuminate\\Auth\\EloquentUserProvider->createModel()
#6 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(131): Illuminate\\Auth\\EloquentUserProvider->retrieveById(1)
#7 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\SessionGuard->user()
#8 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(70): Illuminate\\Auth\\SessionGuard->check()
#9 /Users/mac1/Sites/StudentPortal2/app/Http/Middleware/CheckIfAdmin.php(55): Illuminate\\Auth\\SessionGuard->guest()
#10 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\CheckIfAdmin->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#35 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#36 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#37 /Users/mac1/Sites/StudentPortal2/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#40 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#43 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#48 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#54 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#55 /Users/mac1/Sites/StudentPortal2/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#56 /Users/mac1/Sites/StudentPortal2/server.php(21): require_once('/Users/mac1/Sit...')
#57 {main}
"} 

```

**Comment by pxpm** [comment] 2019-05-09 19:51
try out a `composer dump-autoload`


`#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('')
#4 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(170): spl_autoload_call('')
#5 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/EloquentUserProvider.php(48): Illuminate\\Auth\\EloquentUserProvider->createModel()
#6 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/SessionGuard.php(131): Illuminate\\Auth\\EloquentUserProvider->retrieveById(1)
#7 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\SessionGuard->user()
#8 /Users/mac1/Sites/StudentPortal2/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(70): Illuminate\\Auth\\SessionGuard->check()`

Like i told, it has something to do with your changes in user providers.

Try checking this out: [backpack multi auth](https://github.com/zoutapps/laravel-backpack-multiauth)

Never used it, but can shard you some light.

**Comment by mpixelz** [comment] 2019-05-09 19:55
didn't work but using direct path works so im gonna stick with that and move forward.
