### ISSUE TITLE
backpackforlaravel.com is down

### ISSUE THREAD

**Issue by alashow** [Laravel-Backpack/Base#120] opened 2017-03-19 09:20 UTC
Looks like the site is down.

![screenshot](https://dotjpg.co/KlYh.png)

**Comment by OwenMelbz** [comment] 2017-03-19 10:21
Looks like it's due to the laravel forge issue that cropped by up.

I'm sure @tabacitu will realize, I'll close this as it's not a bug to do with the package

**Closed by OwenMelbz** 2017-03-19 10:21 UTC

**Comment by tabacitu** [comment] 2017-03-19 16:58
Hi @alashow. Thanks a lot for telling me. It's now up and running. Seems like LetsEncrypt is not that reliable after all.

**Comment by alashow** [comment] 2017-03-19 17:03
I wonder, what was wrong with LetsEncrypt?

**Comment by OwenMelbz** [comment] 2017-03-19 17:04
From Taylor Otwell ->

```
Hello,

Unfortunately, a library used by Laravel Forge to obtain LetsEncrypt certificate was forced to rename itself due to a trademark dispute between themselves and LetsEncrypt. This caused some customer's renewal scripts to fail because they are using the old name. This primarily affects customers have active certificates created between May and September of 2016.

If you issue and activate a new LetsEncrypt certificate through the UI this should fix the problem going forward. We are terribly sorry for the inconvenience.

If you have any questions, please feel free to contact us directly.

Thank you,
Taylor
Founder, Laravel Forge
```
