### ISSUE TITLE
How to enable Vue in Backpack

### ISSUE THREAD

**Issue by Patabugen** [Laravel-Backpack/Base#349] opened 2018-12-11 17:07 UTC
# Bug report

### What I did:
I read this on the [Features page](https://backpackforlaravel.com/features):

> Laravel, Bootstrap & jQuery. That’s all you need to know to customize every little bit of your CRUDs. **You don’t need to know Vue, Angular, WebPack, Mix, Less, Sass, NPM etc. But you can use them, if you want.** Of course. 

And then searched the docs for some suggestion as to how to enable Vuejs.

### What I expected to happen:
To find some instructions on where/how to enable Vuejs properly.

### What happened:
I managed to inject Vuejs but it's been causing problems - so I thought I'd find the official guide.

### What I've already tried to fix it:
Read the docs, especially this page: https://backpackforlaravel.com/docs/3.5/base-how-to

### Backpack, Laravel, PHP, DB version:
Backpack: 3.5
Laravel: 5.7

**Comment by tabacitu** [comment] 2018-12-12 09:06
Hi @Patabugen ,

You're totally right, we don't have a guide on how to use Vue with Backpack. 

What problems have you encountered?

**Comment by Patabugen** [comment] 2018-12-14 12:02
Hey @tabacitu 

I've since had a bit of a chat on Gitter about this - that statement on the Features page lead me to assume that there was already a nice way to integrate/build Vue/sass/etc components.

My assumption was actually that I could use the default Laravel build system - but that turned out to be very wrong.

I've worked around it by:

1. Removing jQuery and Bootstrap from npm
1. Removing the jQuery loading bit from resources/js/bootstrap.js
1. Overriding head.blade.php and footer.blade.php to include /js/app.js and /css/app.css

So now I can use the Laravel build system within Backpack. I think my use-case may be non-standard because I've not got a front-end (yet...) - and my misconception of that Feature claim was that Backpack had some kind of build system ready for Vue/Scss/etc - which it seems to totally lack.

**Comment by LarryTX** [comment] 2019-02-24 20:07
Unfortunately, What Backpack has on its website is, perhaps unintentionally, highly misleading. It implies that you can do pretty much anything you want with it. What I'm increasingly coming to see is that Backpack is pretty much a "the Backpack way or the highway." It's very much a locked-in, lock-step environment Contrast that with this blurb from their website:
```
A software that helps Laravel professionals build administration panels - secure areas where administrators login and create, read, update and delete application information. It is not a CMS, it is more a framework that lets you build your own CMS. You can install it in your existing project or in a totally new project.

It’s designed to be flexible enough to allow you to build admin panels for everything from simple presentation websites to CRMs, ERPs, eCommerce, eLearning, etc. We can vouch for that, because we have built all that stuff using Backpack already.
```
As soon as you try to do anything different from their limited way, you'll find no documentation, no support, just being thrown into the catch-as-catch-can world of their Gitter Chatroom to see if anyone has any knowledge ... Actually, what you find there are countless people who have absolutely no knowledge of what you're asking about, and who are only too ready to take up your time offering assistance derived from absolutely no experience, no knowledge, just to confuse everyone who will listen.

The features page talks about a lot more than Vuejs (although in the modern world, that is extremely important). Where's the stuff on Angular, Webpack, Mix, Sass, Nom, Less? Although of these (except maybe for Less, but that's my prejudice) are incredibly important in modern web development. It's inexcusable to fail to include them in documentation and to provide the proper and appropriate hooks to include them in any project. These are the very major players in web development. We're not talking about the huge number of minor players.

**Comment by OwenMelbz** [comment] 2019-02-25 09:29
What?  @LarryTX Backpack works absolutely fine with Vue. We've built a CRM with over 50 Vue components.

Backpack info:

```
➜ composer show | grep "backpack"
backpack/base                         0.9.12             Laravel Backpack's base package, which offers admin authentication and a blank admin panel using AdminLTE
backpack/crud                         3.4.41             Quickly build an admin interface for your Eloquent models, using Laravel 5. Build a CMS in a matter of minutes.
backpack/generators                   1.2.4              Generate files for laravel projects
backpack/logmanager                   2.3.23             An interface to preview, download and delete Laravel log files.
backpack/permissionmanager            2.1.27             Users and permissions management interface for Laravel 5 using Backpack CRUD.
```

Vue components:
```
├── api
│   ├── addresses.js
│   ├── base.js
│   ├── comments.js
│   ├── credentials.js
│   ├── documents.js
│   ├── leads.js
│   ├── notifications.js
│   ├── secretaries.js
│   ├── tasks.js
│   └── users.js
├── app.js
├── bootstrap.js
├── consultant
│   ├── components
│   │   ├── addresses
│   │   │   ├── AddressForm.vue
│   │   │   ├── DeleteConfirm.vue
│   │   │   ├── FormBlock.vue
│   │   │   └── SecretaryForm.vue
│   │   ├── comments
│   │   │   ├── AuditTable.vue
│   │   │   ├── Comment.vue
│   │   │   ├── CommentForm.vue
│   │   │   ├── DateFilter.vue
│   │   │   ├── Timeline.vue
│   │   │   ├── TypeFilter.vue
│   │   │   ├── TypeIcon.vue
│   │   │   └── UserFilter.vue
│   │   ├── credentialing
│   │   │   ├── Credential.vue
│   │   │   ├── CredentialActions.vue
│   │   │   ├── CredentialForm.vue
│   │   │   ├── CredentialSkeleton.vue
│   │   │   ├── FormContainer.vue
│   │   │   ├── Group.vue
│   │   │   ├── LifetimeProgress.vue
│   │   │   └── SignatureForm.vue
│   │   └── documents
│   │       ├── ActionBar.vue
│   │       ├── FilePath.vue
│   │       ├── FileResource.vue
│   │       ├── FolderResource.vue
│   │       ├── Resource.vue
│   │       ├── ResourceGrid.vue
│   │       └── forms
│   │           ├── CreateResourceForm.vue
│   │           ├── RenameResourceForm.vue
│   │           └── UploadResourceForm.vue
│   └── templates
│       ├── AddressBook.vue
│       ├── Comments.vue
│       ├── Credentialing.vue
│       └── Documents.vue
├── dashboard
│   ├── components
│   │   ├── DateTimePicker.vue
│   │   ├── Notifications.vue
│   │   ├── Select2.vue
│   │   ├── compliance
│   │   │   └── ConsultantsModal.vue
│   │   └── tasks
│   │       ├── Editor.vue
│   │       ├── Resolver.vue
│   │       ├── Scheduler.vue
│   │       ├── TaskWidget.vue
│   │       └── UserFilter.vue
│   └── templates
│       └── Dashboard.vue
├── data
│   ├── addresses.js
│   ├── comments.js
│   ├── constants.js
│   ├── credentials.js
│   ├── documents.js
│   ├── leads.js
│   ├── secretaries.js
│   ├── tasks.js
│   ├── tests
│   │   ├── addresses.test.js
│   │   └── credentials.test.js
│   └── users.js
├── events
│   ├── OtherUsersViewing.vue
│   ├── UserViewingConsultant.js
│   ├── bus.js
│   └── index.js
├── leads
│   ├── LeadAudit.vue
│   ├── LeadQuality.vue
│   ├── LeadQuote.vue
│   ├── LeadSidebar.vue
│   ├── LeadStatus.vue
│   ├── comments
│   │   ├── LeadComment.vue
│   │   ├── LeadCommentEditor.vue
│   │   └── LeadComments.vue
│   ├── meta
│   │   ├── LeadMetaData.vue
│   │   └── LeadMetaItem.vue
│   └── offers
│       ├── AppointmentOffer.vue
│       ├── AppointmentOffers.vue
│       ├── BookingNotes.vue
│       └── ConsultantSearch.vue
├── mixins
│   ├── errors.js
│   └── sendsNudges.js
└── utilities
    ├── clipboard.js
    ├── consultant-jump.vue
    ├── route.js
    ├── scroll-to-message.js
    ├── select_or_create.vue
    ├── tiptap-editor.vue
    └── vue-impersonate.vue
```

--

Sure if there's already instantiated jQuery plugins etc they won't be compatible out the box, but that's just jQuery nothing to do with Backpack.

Everything is compiled with the normal laravel mix

```
mix
    .js('resources/assets/js/app.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css');

mix.extract();

mix.setPublicPath('public');

mix.options({
    processCssUrls: false,
    hmrOptions: {
        host: 'localhost',
        port: '3100',
    },
});
```

Then we just pump it out into the `vendor/backpack/layout.blade.php` footer

```
    <script src="{{ mix('js/vendor.js') }}"></script>
    <script src="{{ mix('js/app.js') }}"></script>
```

---

I think you all need to calm down a bit and stop attacking Backpack just because you've failed to impliment something.

Vue 100% works with Backpack if implimented modularly using only what Laravel and Backpack gives you out the box, everything is there and works

**Comment by LarryTX** [comment] 2019-02-25 18:09
Thanks ever so much @OwenMelbz. Your comments totally and absolutely prove the precise point that I was making. Everything you said is wonderful. Now, please show me where it was in the documentation provided on the Backpack site. You see you're so totally into the intuition trap. Somehow, sitting at my desk, I am supposed to intuit all that stuff just sitting here with no help whatsoever. Total intuition devoid of all documentation.

You may have the time to stumble through the code, searching everywhere to try to figure it our. I don't. Sorry, I'm busy producing something that can be used by myself and others. Backpack says you can do something — easily. I expect them to tell me how.

Or perhaps you are such a total genius that you can figure it all out in seconds without having to read code and such. If so, congrats to you. You are such a lucky being. Perhaps you should be promoted to God of the entire Universe. The reality it, the rest of us aren't.

As for the reality, note that @tabacitu stated and I quote, `You're totally right, we don't have a guide on how to use Vue with Backpack.`

Note also all the problems that @Patabugen related. Or did you fail to read them? Or understand them? Or is it just that you figured out how to to through all those complex steps for incorporating VueJs that your related and just want to show how smart you are by making others look stupid. Nice zero-sum way.

And no, Laravel and Back pack don't come with modularity build in. I daresay that you don't understand even the slightest thing about modularity nor have built a modular application with hundreds of models. Witness how hard others have worked at it in multiple frameworks. It's not as easy as you think.

**Comment by OwenMelbz** [comment] 2019-02-25 19:10
Yes, I did read Patabugens message, he didn't list a single "problem" he was actually having - only that he wants instructions as he couldn't figure it out himself - Backpack can't be expected to write a guide for every random library on the internet and how to use it in conjunction with it, especially when none of Backpack even uses them, despite the Issues being a bug tracker, and not a support request, which the contributing guidelines say use StackOverflow for. https://github.com/Laravel-Backpack/Crud/blob/master/CONTRIBUTING.md 

So good luck getting it working @LarryTX I'll be off with the other Gods drinking cocktails on the beach whilst your terrible attitude gets you nowhere. I hope you don't miss any deadlines or get fired or anything 👌 BYEEEEEEEEEE

**Comment by tswonke** [comment] 2019-02-25 19:39
@OwenMelbz 🍸 🍹 🏖 ☀️

**Comment by tabacitu** [comment] 2019-02-26 09:45
Wow. This escalated quickly... :-)) I don't mean to belittle your argument by laughing (you both make good points), but I know how to spot a hot-headed discussion, and this was definitely one :-) I'm sure once you guys cool down, you'll both agree this got too hot, and we can bring the level down a little bit :-) Time does wonders for temper. 

![source-1](https://user-images.githubusercontent.com/1032474/53402216-00b3e280-39ba-11e9-9ce9-a25d23ef4a83.gif)


I also think you seem to be making the same point: **Vue + Backpack is possible, but it's not as easy as reading a guide and doing what it says**. Let's fix that.

@LarryTX - sorry to hear your experience in trying to use Backpack + Vue was frustrating  . I do agree with you, we don't _make it easy_ to use Vue with Backpack. We have not even done _one thing_ to make it easy. As @OwenMelbz  said, Since Backpack v3 doesn't use Vue itself, we did not consider it our responsibility. Sure, Vue is a major player, and a lot of people might want to use it with Backpack. But the same can be said of Angular, React, etc. We can't possibly write guides for how to use every js library with Backpack - we all know the JS ecosystem is booming, and what's the "hot thing" today might be dead in less than a year. I don't think that's the case with Vue.js. In fact, Backpack v4 will use Vue.js components. We're working on that right now. And since Vue.js will already be on page, everything you're talking about there will be a lot easier, in Backpack v4.

But unfortunately Backpack v3 does not use Vue.JS itself. So it doesn't include it, nor make it easy for you to do so. It _can_ be done, as @OwenMelbz has proven, but we have no guide, nor instructions on how to do that. That's the reality of the situation - I totally agree with you, even though I don't agree that our texts are misleading. Yes, we do say you can build anything with Backpack, which I believe to be true, but like any framework in general - we can only provide a few fast ways to do a few stuff. If you want to do things differently than we advise, _of course_ we can't hold your hand. We can only not make it difficult for you. And I think Backpack, in this situation and in others, has walked the fine line between feature-rich and bloat. Between helpful and restrictive. The problems that @Patabugen highlighted are minor, and should be fixable by anyone that has integrated Vue in Laravel & HTML templates before. Bloat vs feature rich, as well as good documentation, is something I concern myself with, every day. I'm sorry to hear you're not satisfied where Backpack v3 is on these fronts. But we're working on it every day. If you don't like it now, maybe check back in a few months - you might like Backpack v4 then.

--

**@OwenMelbz [would you like to write an article on the Backpack blog on how to use Backpack + Vue properly?](https://github.com/Laravel-Backpack/Blog-Articles/issues) I would gladly pay 100 EUR for it**, I've wanted to try this pay-for-article thing for a while now. I know it's not much, but it's _something_, and it would definitely help prevent frustrating experiences like @LarryTX 's. If you have the time to do this, please [open an issue here](https://github.com/Laravel-Backpack/Blog-Articles/issues) and write a markdown file as a PR that fixes it. We'll move the conversation there.

I'm going to close the issue - I think the feedback has been assimilated and a solution proposed. We'll continue the conversation in the PR with the article.

Cheers!

**Closed by tabacitu** 2019-02-26 09:45 UTC
Labels: triage

**Comment by Patabugen** [comment] 2019-02-26 10:22
Blimey - I didn't meant to kick start all that :) For the record, I am loving Backpack - but I am finding it frustrating to achieve the flexibility suggested on the homepage - which I do believe is due to not finding the guides/documentation rather than because it's not possible.

@tabacitu I appreciate you're input. I don't expect to find guides from Backpack for every library out there - but I did expect to find guides for at least some of those listed on the homepage.

The repo you linked to (  https://github.com/Laravel-Backpack/Blog-Articles ) would have been a better place for me to post this request had I known about it. I feel like that collection of articles is all that backpack is missing.

@OwenMelbz I would be very grateful if you could write that article.

**Comment by OwenMelbz** [comment] 2019-02-26 11:04
@tabacitu @Patabugen it already exists honeys https://medium.com/@owenmelbourne/using-backpack-for-laravel-with-vuejs-or-even-react-b6e4ea48caf7

**Comment by Patabugen** [comment] 2019-02-26 11:34
Ah nice, that'd have saved me days of work if I had found it a couple of months ago. (Bit of feedback - it'd be worth clarifying that you're adding the default build to your admin backend, not adding a separate one for Backpack. I found that I also needed to stop Backpack including it's own jQuery - and I'm also having some odd styling issues which I think are related - like super-extra padding around tabs).

**Comment by OwenMelbz** [comment] 2019-02-26 12:23
@Patabugen I think that’s where it starts getting into the grey areas and why I advised you might need to run something like “preset:none”

The problem is that I’m guessing you’ve imported jQuery within your build process AS WELL.

If you were to not to do this, then you wouldn’t have 2 lots loading 😄

Same goes for Bootstrap, if your build process imports bootstrap, then you’ll get styling conflicts like the tabs.

If people are not importing jQuery (were not) and if people are not importing bootstrap (were not) then there’s no problems.

That’s when the grey area starts as we can’t  cover everything that you *might* be doing.

All we can say is check your code and remove duplicates from there instead of trying to remove from backpack maybe?

**Comment by Patabugen** [comment] 2019-02-26 12:27
"The problem is that I’m guessing you’ve imported jQuery within your build process AS WELL."

Backpack imports it by default but so does the Laravel build process. So it'd help if the instructions acknowledged it. Any guides need to assume a default (and up to date) version of Backpack and absolutely nothing else (because as you say - including any other customisations is impossible)

**Comment by OwenMelbz** [comment] 2019-02-26 13:36
The laravel build process ONLY imports it if your running with the bootstrap preset.

If your using react, you’ll know you are. So therefore you will have changed it. If your running a tailwind preset you’ll have run different stuff again.

It might be that you don’t use jQuery so it’s not included anyway. Maybe it’s an existing project etc. if we said “remove this” and it doesn’t exist, it can additionally cause confusion.

As we cannot account for that, there’s no way to give explicit instructions. That is why the article mentions this and says you might need to run the appropriate “preset:none” to remove it.

In my eyes it’s down to the individual developer to configure their dependencies as they need for their project as a part of the setup process and to know what they’re including.

Maybe what you’re after is a list of plugins that Backpack includes by default so you can see if you need to add it in or not?

**Comment by Patabugen** [comment] 2019-03-01 14:26
That's my point - the only level baseline we have is the default shipment of Laravel and Backpack. So the only safe starting point for any tutorial is an unmodified, freshly checked out repo.

People then know what customisation they've made - if they've removed Vue or jQuery - it's their responsibility to know, or if they've added something - that's their responsibility to know how that affects the tutorial.

**Comment by OwenMelbz** [comment] 2019-03-16 13:17
Theres also a example project here with 2 components with some basic guided steps as to whats going on.

https://github.com/OwenMelbz/backpack-laravel-vuejs-demo

**Comment by OwenMelbz** [comment] 2019-03-17 12:26
and for react https://github.com/OwenMelbz/backpack-laravel-react-demo
